os: linux
dist: xenial
language: shell

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

stages:
  - name: main
    if: branch = master

jobs:
  include:
    - stage: main
      name: "Test and build via Dockerfile, then push to Docker Hub"
      script: bash scripts/build.sh
      deploy:
        provider: script
        script: bash scripts/push.sh
        # on:
        #   branch: master
