export const INCREASE_COUNTER = 'INCREASE_COUNTER';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const RESET_COUNTER = 'RESET_COUNTER';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const DELETE_POST_REQUEST = 'DELETE_POST';
export const POSTS_ERROR = 'POSTS_ERROR';
